version: '3.8'

services:
  gorest:
    image: sathappanas/gorestdatadriventesting:1.0
    volumes:
      - ./results:/app/results

  booking:
    image: sathappanas/simpletesting:1.0
    volumes:
      - ./results:/app/results